name: astropedia
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
    sdk: ^3.6.1

dependencies:
    flutter:
        sdk: flutter
    path: ^1.9.0
    sqflite: ^2.4.1
    sqflite_common_ffi: ^2.3.4+4
    sqlite3_flutter_libs: ^0.5.0

dev_dependencies:
    flutter_test:
        sdk: flutter
    flutter_lints: ^5.0.0

flutter:
    uses-material-design: true
